CREATE USER VIDEO IDENTIFIED BY ITQ;
ALTER USER VIDEO quota unlimited on SYSTEM
GRANT ALL PRIVILEGE
TO VIDEO;

connect video/video;

CREATE TABLE member
(
    MEMBER_ID INT NOT NULL PRIMARY KEY,
    LAST_NAME VARCHAR(25) NOT NULL,
    FIRST_NAME VARCHAR(25) NOT NULL,
    ADDRESS VARCHAR(100),
    CITY VARCHAR(30),
    PHONE VARCHAR(15),
    JOIN_DATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE title(
    TITLE_ID INT NOT NULL PRIMARY KEY,
    TITLE VARCHAR(60) NOT NULL,
    DESCRIPTION VARCHAR(400) NOT NULL,
    RATING VARCHAR(4) CHECK(RATING = 'G' OR RATING = 'PG'
    OR RATING = 'R' OR RATING = 'NC17' OR RATING = 'NR'),
    CATEGORY VARCHAR(20) CHECK(
        CATEGORY = 'DRAMA' OR
        CATEGORY = 'COMEDY' OR
        CATEGORY = 'ACTION' OR
        CATEGORY = 'CHILD' OR 
        CATEGORY = 'SCIFY' OR
        CATEGORY = 'DOCUMENTARY'),
    RELEASE_DATE DATE 
);

CREATE TABLE title_copy(
    COPY_ID INT NOT NULL,
    TITLE_ID INT NOT NULL,
    STATUS VARCHAR(15) CHECK(
    STATUS = 'AVAILABLE' OR
    STATUS = 'DESTROYED' OR
    STATUS = 'RENTED' OR
    STATUS = 'RESERVED' 
    ),
    FOREIGN KEY (TITLE_ID) REFERENCES title(TITLE_ID),
    PRIMARY KEY(COPY_ID,TITLE_ID)
); 

CREATE TABLE rental(
    BOOK_DATE DATE DEFAULT SYSDATE PRIMARY KEY NOT NULL,
    MEMBER_ID INT,
    COPY_ID INT, 
    ACT_RET_DATE DATE,
    EXP_RET_DATE DATE DEFAULT SYSDATE+2,
    TITLE_ID INT,
    FOREIGN KEY (MEMBER_ID) REFERENCES member(MEMBER_ID),
    FOREIGN KEY (COPY_ID,TITLE_ID) REFERENCES title_copy(COPY_ID,TITLE_ID)
);

CREATE TABLE reservation(
    RES_DATE DATE PRIMARY KEY NOT NULL,
    MEMBER_ID INT NOT NULL,
    TITLE_ID INT NOT NULL,
    FOREIGN KEY (MEMBER_ID) REFERENCES member(MEMBER_ID),
    FOREIGN KEY (TITLE_ID) REFERENCES title(TITLE_ID)
);

SELECT B.TABLE_NAME, B.CONSTRAINT_NAME, B.CONSTRAINT_TYPE
FROM ALL_CONSTRAINTS B
JOIN USER_TABLES A
on B.TABLE_NAME = A.TABLE_NAME;